export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const GET_QUESTIONS = 'GET_ALL_QUESTIONS';
export const FAIL_QUESTIONS = 'FAIL_QUESTIONS';
export const GET_QUESTIONS_SUBJECT = 'GET_QUESTIONS_SUBJECT';
export const FAIL_QUESTIONS_SUBJECT = 'FAIL_QUESTIONS_SUBJECT';
